### ISSUE TITLE
Warning:  github-pages can't satisfy your Gemfile's dependencies.

### ISSUE THREAD

**Issue by keelancook** [ab/jekyll-theme-tufte#1]
I'm really new to using Gemfiles and Jekyll in general, so excuse me if I'm asking a very simple question. I've searched around and can't seem to find an answer the question. I assume this is user error.

I've tried to include the theme in a Gemfile in both an already established Github pages repo I have with my notes, and I've tried to create a Repo from scratch that includes a Gemile, _config.yml, index.html, etc. But I keep running into the same error.

`Warning:  github-pages can't satisfy your Gemfile's dependencies.`

then, it says: 
>/usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-tufte theme could not be found. (Jekyll::Errors::MissingDependencyException)

I love the simplicity of your theme and would like to use it for working notes in scholarship. I'm an academic in the humanities, so I fumble merely around when it comes to any kind of development work.

**Comment by shichen85** [comment]
> I'm really new to using Gemfiles and Jekyll in general, so excuse me if I'm asking a very simple question. I've searched around and can't seem to find an answer the question. I assume this is user error.
> 
> I've tried to include the theme in a Gemfile in both an already established Github pages repo I have with my notes, and I've tried to create a Repo from scratch that includes a Gemile, _config.yml, index.html, etc. But I keep running into the same error.
> 
> `Warning: github-pages can't satisfy your Gemfile's dependencies.`
> 
> then, it says:
> 
> > /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-tufte theme could not be found. (Jekyll::Errors::MissingDependencyException)
> 
> I love the simplicity of your theme and would like to use it for working notes in scholarship. I'm an academic in the humanities, so I fumble merely around when it comes to any kind of development work.

@keelancook Not sure if you found the answer already or not, but I find that if I delete my `Gemfile.lock` and push the commit to trigger building, the error goes away. My suspicion is that the `Gemfile.lock` file created in my local environment contains dependencies that are not compatible in GitHub's building environment.
